from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import urlparse
from business_operator import *
import os, json

HOST=os.environ.get('HOST','0.0.0.0'); PORT=int(os.environ.get('PORT','8787'))
CSS='''
:root{--bg:#f5f7fb;--panel:#fff;--ink:#172033;--muted:#667085;--line:#e5e7eb;--blue:#2563eb}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:Inter,Segoe UI,Arial,sans-serif}.wrap{max-width:1180px;margin:auto;padding:32px 22px 60px}.top{display:flex;justify-content:space-between;align-items:center;gap:20px}.brand{font-size:26px;font-weight:800}.tag{font-size:12px;background:#eaf1ff;color:#2454c6;padding:7px 10px;border-radius:99px}.hero{margin:26px 0}.hero h1{font-size:42px;line-height:1.05;margin:0 0 12px;max-width:760px}.hero p{font-size:17px;color:var(--muted);max-width:760px;line-height:1.6}.btn{border:0;border-radius:10px;padding:11px 16px;background:var(--blue);color:white;font-weight:700;cursor:pointer}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:24px 0}.card,.panel{background:var(--panel);border:1px solid var(--line);border-radius:16px;box-shadow:0 4px 18px rgba(15,23,42,.04)}.card{padding:20px}.label{font-size:13px;color:var(--muted)}.num{font-size:30px;font-weight:800;margin-top:7px}.panel{padding:22px;margin-top:18px}.panel h2{margin:0 0 7px;font-size:20px}.sub{color:var(--muted);font-size:14px}.issue{border:1px solid var(--line);border-radius:13px;padding:17px;margin-top:12px}.issue-head{display:flex;justify-content:space-between;gap:15px}.sev{font-size:11px;font-weight:800;padding:5px 8px;border-radius:99px}.high{background:#fee2e2;color:#991b1b}.medium{background:#fef3c7;color:#92400e}.issue h3{margin:8px 0 6px;font-size:16px}.issue p{margin:5px 0;color:#4b5563;line-height:1.5}.meta{display:flex;flex-wrap:wrap;gap:9px;margin-top:11px}.chip{font-size:12px;background:#f3f4f6;border-radius:8px;padding:6px 8px}.two{display:grid;grid-template-columns:1fr 1fr;gap:18px}.step{display:flex;gap:12px;margin:15px 0}.circle{width:28px;height:28px;border-radius:50%;background:#eaf1ff;color:#2454c6;display:grid;place-items:center;font-weight:800;flex:0 0 auto}.footer{margin-top:30px;color:var(--muted);font-size:12px;text-align:center}@media(max-width:800px){.cards{grid-template-columns:1fr 1fr}.two{grid-template-columns:1fr}.hero h1{font-size:34px}}
'''
def esc(s):
    import html
    return html.escape(str(s if s is not None else ''))
def money(v): return f"₹{float(v or 0):,.0f}"
def page():
    seed_demo(); b,recs,fs,acts=dashboard_data('demo'); openf=[f for f in fs if f['status']=='open']; impact=sum(float(f['impact'] or 0) for f in openf); high=sum(1 for f in openf if f['severity']=='high'); issue_html=''
    for f in openf:
        issue_html += f'''<div class="issue"><div class="issue-head"><div><div class="label">{esc(f['entity_id'])} · {esc(f['kind']).replace('_',' ')}</div><h3>{esc(f['title'])}</h3></div><span class="sev {'high' if f['severity']=='high' else 'medium'}">{esc(f['severity']).upper()}</span></div><p>{esc(f['message'])}</p><div class="meta"><span class="chip">Confidence {f['confidence']}%</span><span class="chip">Impact {money(f['impact'])}</span><span class="chip">Priority {f['priority']}/100</span></div><p><b>Why flagged:</b> {esc(' · '.join(json.loads(f['reasons'])))}.</p><p><b>Recommended:</b> {esc(f['recommended_action'])}</p></div>'''
    rec_html=''.join(f'<tr><td>{esc(r["entity_id"])}</td><td>{esc(r["customer"])}</td><td>{money(r["amount"])}</td><td>{esc(r["date"])}</td><td>{r["confidence"]}%</td></tr>' for r in recs)
    return f'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Business Operator Demo</title><style>{CSS}table{{width:100%;border-collapse:collapse;margin-top:14px}}th,td{{padding:11px 8px;border-bottom:1px solid var(--line);text-align:left;font-size:13px}}th{{color:var(--muted);font-weight:600}}</style></head><body><main class="wrap"><div class="top"><div class="brand">Business Operator</div><span class="tag">DEMO · SAMPLE DATA</span></div><section class="hero"><h1>Your business data, continuously checked for problems.</h1><p>Business Operator reads orders, payments and invoices, finds mismatches and duplicates, explains why they matter, and puts the most important issues in an attention queue.</p><form method="post" action="/reset"><button class="btn">Run demo analysis</button></form></section><div class="cards"><div class="card"><div class="label">Records checked</div><div class="num">{len(recs)}</div></div><div class="card"><div class="label">Issues found</div><div class="num">{len(openf)}</div></div><div class="card"><div class="label">High priority</div><div class="num">{high}</div></div><div class="card"><div class="label">Potential impact</div><div class="num">{money(impact)}</div></div></div><div class="panel"><h2>Attention queue</h2><div class="sub">What a business owner sees after the automated check.</div>{issue_html}</div><div class="two"><div class="panel"><h2>What the system does</h2><div class="step"><div class="circle">1</div><div><b>Collect</b><div class="sub">Orders, invoices and payment records.</div></div></div><div class="step"><div class="circle">2</div><div><b>Compare</b><div class="sub">Match IDs, amounts, customers and dates.</div></div></div><div class="step"><div class="circle">3</div><div><b>Explain</b><div class="sub">Show confidence, evidence and likely impact.</div></div></div><div class="step"><div class="circle">4</div><div><b>Prioritize</b><div class="sub">Put the most important issues first for a human.</div></div></div></div><div class="panel"><h2>Sample records</h2><div class="sub">All data on this page is fictional.</div><table><tr><th>ID</th><th>Customer</th><th>Amount</th><th>Date</th><th>Confidence</th></tr>{rec_html}</table></div></div><div class="panel"><h2>Why a business would care</h2><p class="sub">Instead of manually checking thousands of records, a team gets a short list of exceptions that deserve attention. The product is designed to reduce checking work and surface potential money or data problems earlier.</p></div><div class="footer">Demo only · fictional data · no bank credentials or real customer information</div></main></body></html>'''
class Handler(BaseHTTPRequestHandler):
    def log_message(self,*a): pass
    def send(self,body,status=200,ctype='text/html; charset=utf-8'):
        raw=body.encode(); self.send_response(status); self.send_header('Content-Type',ctype); self.send_header('Content-Length',str(len(raw))); self.end_headers(); self.wfile.write(raw)
    def do_GET(self):
        if urlparse(self.path).path=='/health': self.send(json.dumps({'ok':True,'demo':True}),ctype='application/json'); return
        self.send(page())
    def do_POST(self):
        if urlparse(self.path).path=='/reset': seed_demo()
        self.send('<meta http-equiv="refresh" content="0;url=/">')
if __name__=='__main__':
    init_db(); ensure_business('demo','Demo Retailer'); print(f'Business Operator Demo running at http://{HOST}:{PORT}'); ThreadingHTTPServer((HOST,PORT),Handler).serve_forever()
